### ISSUE TITLE
Any ability to adjust to allow multiple files being signed - either at once or multiple runs of the action in the same job?

### ISSUE THREAD

**Issue by JeremiahChurch** [lando/code-sign-action#12]
Really love the action, it's saved a ton of time and copy/pasting of code signing stuff through various jobs.

Running into a use case that would love ideas/feedback on.

Trying to build and sign two files in the same GH job for a mac app signing. 

Attempting to run the action a second time in a job fails with the error below.

```
Signsetup
  security: SecKeychainCreate macos-build.keychain: A keychain with the same name already exists.
```

And it doesn't look like there is any mechanism to pass multiple files in either to the action (or the underlying codesign)

Any thoughts on the best way to sign multiple files in a single job using the action rather than manually building the `codesign` command line?

ie:
```
- name: Sign Staging Binary
        uses: lando/code-sign-action@v3
        with:
          file: staging-app
          certificate-data: ${{ secrets.APPLE_CERT_DATA }}
          apple-team-id: ${{ secrets.APPLE_TEAM_ID }}
          certificate-password: ${{ secrets.APPLE_CERT_PASSWORD }}
- name: Sign Prod Binary
        uses: lando/code-sign-action@v3
        with:
          file: prod-app
          certificate-data: ${{ secrets.APPLE_CERT_DATA }}
          apple-team-id: ${{ secrets.APPLE_TEAM_ID }}
          certificate-password: ${{ secrets.APPLE_CERT_PASSWORD }}
```

vs 

```
- name: Sign Staging Binary
        uses: lando/code-sign-action@v3
        with:
          file: staging-app
          certificate-data: ${{ secrets.APPLE_CERT_DATA }}
          apple-team-id: ${{ secrets.APPLE_TEAM_ID }}
          certificate-password: ${{ secrets.APPLE_CERT_PASSWORD }}
- name: Sign Production Binary
        run: codesign --sign <yada yada> prod-app
```

**Comment by devantler** [comment]
I would love this as well!

I imagine something like this:

```yaml
# One file
- name: Sign Binary
  uses: lando/code-sign-action@v3
  with:
    files: [staging-app]
    certificate-data: ${{ secrets.APPLE_CERT_DATA }}
    apple-team-id: ${{ secrets.APPLE_TEAM_ID }}
    certificate-password: ${{ secrets.APPLE_CERT_PASSWORD }}
```

```yaml
# Multiple files
- name: Sign Binaries
  uses: lando/code-sign-action@v3
  with:
    files: 
    - staging-app
    - prod-app
    certificate-data: ${{ secrets.APPLE_CERT_DATA }}
    apple-team-id: ${{ secrets.APPLE_TEAM_ID }}
    certificate-password: ${{ secrets.APPLE_CERT_PASSWORD }}
```

In short, the `file` key should be updated to `files`, and support one to many files.
